# PANDAS AND NUMPY

In [7]:
import pandas as pd
import numpy as np

In [10]:
import os
print(os.listdir())

['Pandas_and_NumPy.ipynb', 'DataWranging8:21...csv', 'DataWranging8:21.numbers', '.ipynb_checkpoints', 'DW8.21.ipynb']

In [13]:
list1 = [1,2,3]
list2 = [4,5,6]
list2

[4, 5, 6]

In [16]:
array_1 = np.array([1,2,3])
array_2 = np.array([4,5,6])

In [21]:
array_3= array_1+ array_2
array_3

array([5, 7, 9])

In [18]:
list3= list1+ list2

In [19]:
list3

[1, 2, 3, 4, 5, 6]

In [22]:
array_3**(0.5)

array([2.23606798, 2.64575131, 3.        ])

* PANDAS

In [25]:
import random

In [42]:
# creating pandas data frame
df1= pd.DataFrame(np.random.randn(5,8))
columns= '1 2 3 4 5 6 7'. split('1')
re

In [43]:
df1

,0,1,2,3,4,5,6,7
0,0.241296,-1.621834,0.907847,1.395748,-1.426354,-3.137847,0.935551,0.475401
1,1.159832,1.168182,-1.110649,1.421939,-1.109068,0.092161,-0.647375,-0.804632
2,1.074636,-0.047758,-0.096644,-1.377280,0.070345,-0.744154,-0.152511,-1.938115
3,1.454896,-1.618214,0.081820,-0.284382,0.106028,-1.827399,0.076181,-1.330822
4,1.470281,-0.267303,-0.042809,-1.940856,-0.653494,-1.409377,0.872394,1.360449

In [45]:
df2= pd.DataFrame(np.random.randn(10,5))

In [46]:
df2

          0         1         2         3         4
0  0.804363 -0.441852 -0.246334 -1.321868  0.809739
1  0.011133 -0.509506  0.921680 -0.199276  0.668732
2 -2.175045  0.143762  0.341826 -0.278778  1.003641
3  0.751848  0.817968  0.885344 -2.028980 -1.235913
4 -0.121447  0.139911  0.350188  0.721538 -0.608873
5 -2.509282  1.419968 -0.664462 -1.148940  0.119690
6 -2.059367  0.283217  1.761707  1.551724 -1.946533
7  0.178179 -1.874796 -2.113299 -0.019017 -1.886652
8 -0.224160  1.197357 -0.145655  0.253475  0.717405
9  0.165921  0.559485 -0.066255 -0.911755  1.676417

In [47]:
df1.rename(columns ={0:"Column1", 
           1:"Column2", 
2:"Column3", 
3:"Column4", 
4:"Column5"})

    Column1   Column2   Column3   Column4   Column5
0  0.416588  1.643327  1.298312  1.242726 -1.261989
1  0.484312  0.808281  1.223255 -0.984209  0.453657
2 -1.448251 -0.700012  2.067262  0.646860  0.297619
3  0.349299 -1.877910 -0.556783 -0.472288 -0.271432
4  1.381932  1.221077 -1.382061  0.813098 -1.288268
5 -0.347937  0.809980 -0.436362  0.559581 -2.035824
6 -0.125932 -0.032082 -1.096474 -0.231248  1.748284
7  0.761974 -1.113645 -0.644152  0.383400 -0.089748
8 -0.921053 -0.001996  1.545390  0.188540  0.730140
9  1.488995  0.285901 -0.726199 -0.282296 -1.016148

In [48]:
import glob
files = glob.glob("*.csv")
print(files)
df = pd.read_csv(files[0])
df.head()

['DataWranging8:21...csv']

,customer_id,name,age,city,signup_date,price,email,membership
0,C-1001,Ann Smith,25,New York,2026-01-15,"$1,299.00",ann.smith@example.com,gold
1,C-1002,Brian Ochoa,thirty,Boston,2026-01-17,45.50,b.ochoa@example.com,silver
2,C-1003,Carla Reyes,41,Chicago,2026-01-19,230.00,carla.r@example.com,gold
3,C-1004,Devon Lee,NaN,Boston,2026-01-21,$89.99,devon.lee@example.com,bronze
4,C-1005,Elena Ford,34,new york,2026-01-22,"1,050.00",e.ford@example.com,gold